env: production

db:
  host: ribbonwall.cluster-coainxnx6ynm.us-west-2.rds.amazonaws.com
  name: ribbonwall_db
  port: 3306
  sslmode: disable
  connectionName: localhost
  debugLog: false

auth:
  audience: admin.ribbonwall.ca
  issuer: https://ribbonwall.auth0.com/
  domain: ribbonwall.auth0.com
  clientID: BpEKugicW7UkdXmWatcHLbw5iNf4wp5l
  redirectURL: http://dev.ribbonwall.ca/callback
  loginURL: http://dev.ribbonwall.ca/login
  homeURL: http://dev.ribbonwall.ca/